export const getCountryFlag = (countryCode: string): string => {
    const flagMap: Record<string, string> = {
        USA: "🇺🇸",
        CAN: "🇨🇦",
        GBR: "🇬🇧",
        DEU: "🇩🇪",
        FRA: "🇫🇷",
        JPN: "🇯🇵",
        KOR: "🇰🇷",
        CHN: "🇨🇳",
        AUS: "🇦🇺",
        BRA: "🇧🇷",
        MEX: "🇲🇽",
        RUS: "🇷🇺",
        SWE: "🇸🇪",
        NOR: "🇳🇴",
        DNK: "🇩🇰",
        FIN: "🇫🇮",
        NLD: "🇳🇱",
        ESP: "🇪🇸",
        ITA: "🇮🇹",
        POL: "🇵🇱",
        BEL: "🇧🇪",
        AUT: "🇦🇹",
        CHE: "🇨🇭",
        CZE: "🇨🇿",
        HUN: "🇭🇺",
        PRT: "🇵🇹",
        GRC: "🇬🇷",
        TUR: "🇹🇷",
        ISR: "🇮🇱",
        IND: "🇮🇳",
        THA: "🇹🇭",
        SGP: "🇸🇬",
        MYS: "🇲🇾",
        IDN: "🇮🇩",
        PHL: "🇵🇭",
        VNM: "🇻🇳",
        TWN: "🇹🇼",
        HKG: "🇭🇰",
        NZL: "🇳🇿",
        ZAF: "🇿🇦",
        ROU: "🇷🇴",
        BGR: "🇧🇬",
        HRV: "🇭🇷",
        SRB: "🇷🇸",
        SVN: "🇸🇮",
        SVK: "🇸🇰",
        EST: "🇪🇪",
        LVA: "🇱🇻",
        LTU: "🇱🇹",
        UKR: "🇺🇦",
    };
    return flagMap[countryCode.toUpperCase()] || "🌍";
};

export const getCountryName = (countryCode: string): string => {
    const countryNames: Record<string, string> = {
        USA: "United States",
        CAN: "Canada",
        GBR: "United Kingdom",
        DEU: "Germany",
        FRA: "France",
        JPN: "Japan",
        KOR: "South Korea",
        CHN: "China",
        AUS: "Australia",
        BRA: "Brazil",
        MEX: "Mexico",
        RUS: "Russia",
        SWE: "Sweden",
        NOR: "Norway",
        DNK: "Denmark",
        FIN: "Finland",
        NLD: "Netherlands",
        ESP: "Spain",
        ITA: "Italy",
        POL: "Poland",
        BEL: "Belgium",
        AUT: "Austria",
        CHE: "Switzerland",
        CZE: "Czech Republic",
        HUN: "Hungary",
        PRT: "Portugal",
        GRC: "Greece",
        TUR: "Turkey",
        ISR: "Israel",
        IND: "India",
        THA: "Thailand",
        SGP: "Singapore",
        MYS: "Malaysia",
        IDN: "Indonesia",
        PHL: "Philippines",
        VNM: "Vietnam",
        TWN: "Taiwan",
        HKG: "Hong Kong",
        NZL: "New Zealand",
        ZAF: "South Africa",
        ROU: "Romania",
        BGR: "Bulgaria",
        HRV: "Croatia",
        SRB: "Serbia",
        SVN: "Slovenia",
        SVK: "Slovakia",
        EST: "Estonia",
        LVA: "Latvia",
        LTU: "Lithuania",
        UKR: "Ukraine",
    };
    return countryNames[countryCode.toUpperCase()] || countryCode.toUpperCase();
};
